-- WARNING: This schema is for context only and not meant to be executed directly.
-- Table order and constraints may not be valid for one-pass execution.
-- Generated for Tiwhanawhana Orchestrator – the living Awa of Translation, Vision, and Memory.

CREATE SCHEMA IF NOT EXISTS tiwhanawhana;

-- ==========================================================
-- 🔮 MAURI LOGS — tracks every awakening, breath, and sync
-- ==========================================================
CREATE TABLE tiwhanawhana.mauri_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phase text DEFAULT 'awakening',
  tohu_id text,
  message text,
  created_at timestamptz DEFAULT now(),
  meta jsonb,
  CONSTRAINT mauri_logs_pkey PRIMARY KEY (id)
);

-- ==========================================================
-- 📜 TASK QUEUE — orchestrator job scheduling / flow control
-- ==========================================================
CREATE TABLE tiwhanawhana.task_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_type text,
  payload jsonb,
  status text DEFAULT 'pending',
  priority integer DEFAULT 1,
  retries integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz,
  completed_at timestamptz,
  CONSTRAINT task_queue_pkey PRIMARY KEY (id)
);

-- ==========================================================
-- 👁️ OCR LOGS — raw extraction of image text content
-- ==========================================================
CREATE TABLE tiwhanawhana.ocr_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_name text,
  file_url text,
  text_content text,
  language_detected text,
  meta jsonb,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT ocr_logs_pkey PRIMARY KEY (id)
);

-- ==========================================================
-- 🌐 TRANSLATIONS — multilingual corpus memory
-- ==========================================================
CREATE TABLE tiwhanawhana.translations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ocr_id uuid,
  source_lang text,
  target_lang text,
  source_text text,
  translated_text text,
  model_used text,
  confidence numeric,
  meta jsonb,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT translations_pkey PRIMARY KEY (id),
  CONSTRAINT translations_ocr_fkey FOREIGN KEY (ocr_id)
      REFERENCES tiwhanawhana.ocr_logs (id)
      ON DELETE SET NULL
);

-- ==========================================================
-- 🧠 EMBEDDINGS — vectorized mauri memory
-- ==========================================================
CREATE TABLE tiwhanawhana.embeddings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  translation_id uuid,
  text_chunk text,
  embedding vector(1536),
  meta jsonb,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT embeddings_translation_fkey FOREIGN KEY (translation_id)
      REFERENCES tiwhanawhana.translations (id)
      ON DELETE CASCADE
);

-- ==========================================================
-- 🌊 TI MEMORY — persistent recall for the orchestrator
-- ==========================================================
CREATE TABLE tiwhanawhana.ti_memory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  memory_type text DEFAULT 'reflection',
  content text,
  embedding vector(1536),
  related_task uuid,
  meta jsonb,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT ti_memory_pkey PRIMARY KEY (id),
  CONSTRAINT ti_memory_task_fkey FOREIGN KEY (related_task)
      REFERENCES tiwhanawhana.task_queue (id)
      ON DELETE SET NULL
);

-- ==========================================================
-- 🔐 META TABLE — rotation, signature, source validation
-- ==========================================================
CREATE TABLE tiwhanawhana.meta (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp timestamptz DEFAULT now(),
  rotation_nonce text NOT NULL,
  signature text NOT NULL,
  source text,
  created_at timestamptz DEFAULT now()
);

-- ==========================================================
-- 📈 INDEXES
-- ==========================================================
CREATE INDEX ON tiwhanawhana.embeddings USING ivfflat (embedding vector_l2_ops);
CREATE INDEX ON tiwhanawhana.ti_memory USING ivfflat (embedding vector_l2_ops);
CREATE INDEX ON tiwhanawhana.translations (source_lang, target_lang);
CREATE INDEX ON tiwhanawhana.task_queue (status, priority);

-- ==========================================================
-- 🕯️ COMMENTARY (for Supabase metadata)
-- ==========================================================
COMMENT ON SCHEMA tiwhanawhana IS 'Tiwhanawhana orchestrator schema: OCR, translation, embeddings, mauri, and awa flow tracking.';
COMMENT ON TABLE tiwhanawhana.mauri_logs IS 'Logs each awakening and mauri update of the orchestrator.';
COMMENT ON TABLE tiwhanawhana.embeddings IS 'Stores vectorized memory chunks for semantic recall via pgvector.';
COMMENT ON TABLE tiwhanawhana.ti_memory IS 'Long-term memory for Tiwhanawhana, linked to task_queue.';
COMMENT ON TABLE tiwhanawhana.translations IS 'Translated text content from OCR logs or imported sources.';
COMMENT ON TABLE tiwhanawhana.ocr_logs IS 'Raw OCR outputs with language detection and metadata.';
